In [2]:
import nltk 
import pandas as pd 
import numpy as np

In [27]:
import itertools
from nltk.collocations import BigramCollocationFinder as bcf
from nltk.metrics import BigramAssocMeasures as bam

In [5]:
k = pd.read_csv('/Users/sharathg/Desktop/fglndflg/feel_data')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,1,2,3,5,6,8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
k.head()

,bookID,title,author,review,rating,reviewerName,rev_lang,sentiment,feel
0,3,Harry Potter and the Sorcerer's Stone,J.K. Rowling,I'm going to keep this brief since there isn't...,4.44,Lora,en,0.9955,Positive
1,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,"""Read Harry Potter!"" they said. ""It'll be fun!...",4.54,Cait (Paper Fury),en,0.9991,Positive
2,7,"The Harry Potter Collection (Harry Potter, #1-6)",J.K. Rowling,I do not own this spiffy box set of Harry Pott...,4.73,Jen Holman,en,0.9852,Positive
3,9644,Why I Write,George Orwell,"Part 56 in the ""Another autobiographical revie...",4.04,Matthias,en,0.9993,Positive
4,3732,Selected Poems of Herman Melville,Herman Melville,Herman MelvilleÛªs poetry is an enigma. The m...,3.90,Keith,en,0.9705,Positive

In [22]:
l =''
for i in k.review:
    k+=i

TypeError: Could not operate 'I\'m going to keep this brief since there isn\'t much to say that hasn\'t already been said. *clears throat*I think the reason I waited so long to read this series is because I just couldn\'t imagine myself enjoying reading about an eleven-year-old boy and his adventures at a school of wizardry. I thought it would be too juvenile for my taste. I was wrong, of course.I can honestly say that I loved every minute of this. It\'s a spectacular little romp with funny, courageous, and endearing characters that you can\'t help but love.It has talking chess pieces, singing hats, a giant three-headed dog named Fluffy, a hilarious giant with a dragon fetish, a master wizard that\'s just a little bit crazy, mail carrier owls, goblins running a bank, unicorns, centaurs(!), trolls . . . and probably much more that I\'m forgetting. And then there\'s the lead characters: Hermione, the young scholar who starts out prim and up-tight but soon becomes a true friend; Ron, the boy who has little money but who has an abundance of family and loyalty to his friends to make up for it; and then there\'s Harry, the boy who starts out sleeping in a closet and ends up being a hero. Harry is kind to those that deserve it, fearless when it counts the most, and wonderfully intelligent. What\'s not to love? In regards to the ending: (view spoiler)[I feel silly saying this about a middle grade novel, but I didn\'t suspect Quirrell a bit! If there were hints that he was the true culprit and not Snape, I obviously missed them. (hide spoiler)]FAVORITE QUOTE: "But from that moment on, Hermione Granger became their friend. There are some things you can\'t share without ending up liking each other, and knocking out a twelve-foot mountain troll is one of them."Now, if you\'ll excuse me, I\'m off to start Harry Potter and the Chamber of Secrets.*******************************************************My reviews of other titles in this series:Harry Potter and the Chamber of Secrets' with block values unsupported operand type(s) for +: 'float' and 'str'

In [25]:
l = k.review.loc[k.author =="J.K. Rowling"].unique()

In [26]:
l[1]

'"Read Harry Potter!" they said. "It\'ll be fun!" they said. "Our childhood was built on Harry Potter!" they said.WELL YOUR CHILDHOODS WERE ALL HORRIBLE. OMG WHAT IS THIS BOOK? WHAT IS THIS MESS I\'M IN?? Excuse me, but that large salty lake where my life used to be is my tears. Yes, yes, this means I loved it. But SERIOUSLY. Nooooot okay. At the end there, especially, I couldn\'t put the audio down so I was wandering about my house in a blind daze listening instead.And because every human and their fluffy poodle has probably sensibly reviewed this book, BAH. I\'m just going to make a list of things I loved and things I didn\'t. My Intense And Passionate LOVES:\x89Û¢ Harry + Ginny = yes. I was dubious at first. Like I think romance is NOT JKR\'s strong point...plus when she gets to a romantic scene she ends the chapter. HHAHAH. ADORABLE. (Not that I minded, I just...I think she\'s not good at romance.) But omg, there was that moment after the Quidditch match??? YUP. You know what I\'m talking about. Excuse me, my heart just ran around in circles screaming and shipping.\x89Û¢ Hermione: I adore her, but...I gotta admit, she was a little bit too stuffy. BUT I STILL LOVE HER. I love her love for learning.\x89Û¢ I also adore how sensible Ginny is. \x89Û¢ Fred and George\'s joke shop gives life. Also death, probs, but liiiiife.\x89Û¢ I am utterly in LOVE with the whole concept of Hogwarts. I mean, I think it\'s stupid that they have to write with a quill and ink (can\'t they just enchant the quill to write for them?) and they seem to get an excessive amount of homework, BUT. It\'s all so vivid and detailed and it literally feels like Hogwarts is A REAL PLACE. I totally get why people wail about their letters going missing. \x89Û¢ Speaking of detail...me likey. I always felt inside the story.\x89Û¢ Plus the audio book (narrated by Jim Dale) is GREAT. I totally recommend it. I think Hermione\'s voice had a tendency to sound like an insufferable goat, but I got used to it. Harry\'s voice was perfection. \x89Û¢ I also particularly liked Harry in this book. I JUST LOVE HARRY. <3 He\'s snarky, but he\'s lost some of the angriness from bk 5. He\'s got snarky quips at the ready, but he\'s also intensely...good. Like he\'s just a really GOOD chap, who makes bad decisions but really means well. ZOMG. *flails about* He was definitely my favourite character in this book. \x89Û¢ ALSO DUMBLEDORE WAS GREAT. I love Dumbledore and how he\'s always polite and kind and smiley. (view spoiler)[ CAN WE TALK A MINUT EHOW I\'M NOT OKAY THAT HE\'S DEAD?!??!?!? LIKE WHAT EVEN THE FLYING HECK OF BROOMS NEST TAILS. THAT DOESN\'T MAKE SENSE. BUT IT SHOULDN\'T. BECAUSE NOTHING MAKES SENSE. Dumbledore. no. Come baaaaaaaack. *breaks down into a mess* I am also intensely furious that his weakening himself to get the horcrux was useless. MAD. Okay? I AM MAD. Character deaths where they failed are the worst there are.  (hide spoiler)]My Intense and Passionate LOATHES:(Hhahahha...you ready for this?)\x89Û¢ Okay so, question: WHY do they sometimes go places and buy food...and sometimes they just magic it? Like Mrs. Weasely magics onion soup out of nothing for Harry. But in the next chapter, Harry and Ron are peeling sprouts. LIKE WUT. This makes no sense to me. \x89Û¢ Why didn\'t Dumbledore pour the evil potion on the ground instead of drinking it? Just wannna know...\x89Û¢ How the FLYING FRIKKIN BROOMSTICKS can anyone possibly convince me Snape is still on the good side? Because I don\'t even care. He can go abra kadabra himself to Timbuktu and DIE THERE THANKS. There is no repentance after this. I don\'t even care what the "reason" is in book 7, but Harry: you are an idiot to name your kid after Snape. \x89Û¢ I HOPE SNAPE DIES.\x89Û¢ DID I MENTION MY HATE FOR SNAPE YET???????\x89Û¢ Oh and another thing...I am so angry at Snape arghhhqqwqq.\x89Û¢ Okay. Good now. I\'m calm. Thank you. \x89Û¢ HAHHAHHAHAHTE SNAPE.\x89Û¢ Yes, I truly am calm this time. I\'m good.\x89Û¢ So. I also am fairly annoyed about Voldermort\'s (Tom Riddle) backstory. Because he read like he was straight out of a psychopath text book...which I found monstrously unimaginative. Attractive, calm, subtle bully, kleptomaniac, limited emotional reach, charmer, smooth...blah blah. Yes. I can just read a book about psychopaths and that\'s Voldey\'s description. I wish there\'d been a little more ingenuity in there.\x89Û¢ I really also dislike Ron. I KNOW. Travesty. But he\'s a bully! He was bullying first year\'s the whole time...turfing tem off chairs, scaring them, bossing them around, taking stuff off them in the name of "prefect". Like how is that good?? How is that okay??? I will not forgive Ron for all this. And also the fact that he\'s a downright BRUTE to Hermione. How can I ship them when he\'s so rude and demeaning to her?? I DON\'T. Hermione deserves better. And I don\'t buy the "She completes him by sorting him out" because I think all humans should take responsibility for their actions. Hermione shouldn\'t HAVE to force Ron into a better person and be his conscious. AGH. \x89Û¢ Not shipping that. ^^\x89Û¢ Okay, I\'m done. But just *whispers* I hate hate hate Snape. So basically YES, I had a fantastic time with this book. I loved the audio. I loved the story. I loved Harry and the world just feels so big and rich and visual. I get the intense fandom for this I DO GET IT. After being so angry and 1000% done in with book 3, I can successfully say I can\'t WAIT to read the last book now. And then watch all the movies. And then I\'ll finally be caught up, omg. Only took me like 10 years.'

In [35]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import WordPunctTokenizer
from nltk.collocations import BigramCollocationFinder
from nltk.metrics import BigramAssocMeasures

In [36]:
text = ['cant railway station','citadel hotel',' police stn']

In [37]:
tes =' This is, a great time, to discuss the matter .''muhane is the shit bro '

In [42]:
tes.split(" ")

['', 'This', 'is', 'a', 'great', 'time', 'to', 'discuss', 'the', 'matter', '.']

In [47]:
def get_bigrams(myString):
    tokenizer = WordPunctTokenizer()
    tokens = tokenizer.tokenize(myString)
    stemmer = PorterStemmer()
    bigram_finder = BigramCollocationFinder.from_words(tokens)
    bigrams = bigram_finder.nbest(BigramAssocMeasures.chi_sq, 500)
    for bigram_tuple in bigrams:
        x = "%s %s" % bigram_tuple
        tokens.append(x)

    result = [' '.join([stemmer.stem(w).lower() for w in x.split()]) for x in tokens if x.lower() not in stopwords.words('english') and len(x) > 8]
    return result

In [49]:
get_bigrams(l[1])

['childhood',
 'childhood',
 'serious',
 'especi',
 'wander',
 'listen',
 'passion',
 'quidditch',
 'scream',
 'excess',
 'liter',
 'recommend',
 'insuffer',
 'perfect',
 'particularli',
 'angri',
 'intens',
 'decis',
 'definit',
 'favourit',
 'charact',
 'dumbledor',
 'dumbledor',
 'dumbledor',
 'baaaaaaaack',
 'intens',
 'weaken',
 'charact',
 'passion',
 'sometim',
 'sometim',
 'dumbledor',
 'broomstick',
 'repent',
 'arghhhqqwqq',
 'hahhahhahaht',
 'voldermort',
 'backstori',
 'psychopath',
 'monstrous',
 'unimagin',
 'attract',
 'kleptomaniac',
 'emot',
 'psychopath',
 'descript',
 'ingenu',
 'downright',
 'demean',
 'complet',
 'respons',
 'consciou',
 'basic',
 'fantast',
 'success',
 ':( hhahahha',
 'all horribl',
 'also dumbledor',
 'after be',
 'also death',
 'becaus noth',
 'broom nest',
 'childhood were',
 'charact death',
 'come baaaaaaaack',
 'dead ?!??!?!?',
 'die there',
 'dumbledor wa',
 'frikkin broomstick',
 'good chap',
 'just wannna',
 'loath :(',
 'mention my',
 'minut ehow',
 'my intens',
 'nest tail',
 'noth make',
 'of broom',
 'onli took',
 'our childhood',
 'quidditch match',
 'real place',
 'she complet',
 'there thank',
 'tom riddl',
 'well your',
 'weas magic',
 'yet ???????\x89',
 'your childhood',
 'abra kadabra',
 'angri from',
 'anoth thing',
 'anyon possibl',
 'bad decis',
 'basic ye',
 'blind daze',
 'caught up',
 'circl scream',
 'daze listen',
 'downright brute',
 'emot reach',
 'even care',
 'everi human',
 'evil potion',
 'excess amount',
 'fairli annoy',
 'favourit charact',
 'felt insid',
 'fluffi poodl',
 'found monstrous',
 'gotta admit',
 'ha probabl',
 'human should',
 'insuffer goat',
 'intens fandom',
 'joke shop',
 'larg salti',
 'limit emot',
 'lost some',
 'magic onion',
 'monstrous unimagin',
 'more ingenu',
 'onion soup',
 'particularli like',
 'peel sprout',
 'peopl wail',
 'poodl ha',
 'possibl convinc',
 'prefect ".',
 'probabl sensibl',
 'psychopath text',
 'romant scene',
 'salti lake',
 'sensibl review',
 'shop give',
 'should take',
 'strong point',
 'success say',
 'take respons',
 'take stuff',
 'too stuffi',
 'turf tem',
 'whi peopl',
 'potter !"',
 ') backstori',
 '?!??!?!? like',
 'fli frikkin',
 'fli heck',
 'it shouldn',
 'make sens',
 'make sens',
 'nooooot okay',
 'okay that',
 'passion loath',
 'passion love',
 'so basic',
 'that doesn',
 'the fli',
 'thi book',
 'thi mess',
 'thi make',
 'wa great',
 'alway felt',
 'alway polit',
 'becaus everi',
 'better person',
 'break down',
 'bulli first',
 'by sort',
 'complet him',
 'death where',
 'deserv better',
 'first year',
 'give life',
 'go place',
 'go miss',
 'ground instead',
 'hide spoiler',
 'hi consciou',
 'hi weaken',
 'intens furiou',
 'kadabra himself',
 'know ...\x89',
 'lake where',
 'letter go',
 'listen instead',
 'liter feel',
 'littl bit',
 'littl more',
 'll final',
 'make bad',
 'match ???',
 'mean well',
 'name your',
 'narrat by',
 'next chapter',
 'not forgiv',
 'off chair',
 'plu when',
 'ran around',
 'romanc .)',
 'sensibl ginni',
 'snarki quip',
 'sort him',
 'spoiler )[',
 'spoiler )]',
 'stuff off',
 'subtl bulli',
 'then watch',
 'total recommend',
 'view spoiler',
 'wannna know',
 'weaken himself',
 'who make',
 'whole concept',
 'hate hate',
 'dumbledor pour',
 'for snape',
 'hahhahhahaht snape',
 'hope snape',
 'just love',
 'love harri',
 'snape die',
 'snape yet',
 'still love',
 'thank you',
 'what even',
 'an excess',
 'an insuffer',
 'fantast time',
 'how sensibl',
 'kid after',
 'moment after',
 'no repent',
 'potion on',
 'question :',
 'realli good',
 'repent after',
 'straight out',
 'their action',
 'their fluffi',
 'their letter',
 'excus me',
 'they said',
 'also intens',
 'snape arghhhqqwqq',
 'all human',
 'are peel',
 'be caught',
 'dislik ron',
 'dubiou at',
 'fail are',
 'final be',
 'forc ron',
 'forgiv ron',
 'scene she',
 'sound like',
 'watch all',
 'not ship',
 'blah blah',
 'care what',
 'down into',
 'got snarki',
 'know what',
 'life use',
 'sometim go',
 'voic had',
 'harri potter',
 'but serious',
 'hermion deserv',
 'hermion shouldn',
 'am fairli',
 'am utterli',
 'boss them',
 'definit my',
 'end there',
 'good side',
 'm talk',
 'my favourit',
 'scare them',
 'ship them',
 'wish there',
 'worst there',
 '( narrat',
 '* whisper',
 'about voldermort',
 'about psychopath',
 'annoy about',
 'convinc me',
 'flail about',
 'talk about',
 'wail about',
 'wander about',
 'whisper *',
 '?? excus',
 'like what',
 'ador her',
 'ador how',
 'audio down',
 'realli mean',
 'whole time',
 'you readi',
 'thi book',
 'broomstick can',
 'also dislik',
 'also particularli',
 'can anyon',
 'can success',
 'drink it',
 'fandom for',
 'for learn',
 'it liter',
 'noth for',
 'recommend it',
 'respons for',
 '" prefect',
 'but liiiiif',
 'decis but',
 'at romanc',
 'feel like',
 'like hogwart',
 'total get',
 'write with',
 'himself to',
 'read harri',
 'speak of',
 'amount of',
 'arghhhqqwqq .\x89',
 'concept of',
 'heart just',
 'just enchant',
 'just magic',
 'learn .\x89',
 'liiiiif .\x89',
 'like harri',
 'of detail',
 'of drink',
 'of homework',
 'of noth',
 'they fail',
 'they have',
 'they seem',
 'world just',
 'love dumbledor',
 'the audio',
 'charact in',
 'childhood wa',
 'fact that',
 'furiou that',
 'horcrux wa',
 'in circl',
 'ingenu in',
 'last book',
 'review thi',
 'stupid that',
 'text book',
 'that larg',
 'that moment',
 'utterli in',
 'wa built',
 'wa bulli',
 'wa definit',
 'wa dubiou',
 'wa perfect',
 'wa straight',
 'wa useless',
 'wa wander',
 '? becaus',
 'them around',
 'them when',
 'think romanc',
 '... turf',
 '... which',
 'hhahahha ...',
 'detail ...',
 'point ...',
 'smooth ...',
 'thing ...',
 'and passion',
 'and becaus',
 'intens and',
 'love with',
 'after snape',
 'hate snape',
 'read like',
 'time with']

In [100]:
import pandas as pd 
import numpy as np 
q = pd.read_csv('/Users/sharathg/Desktop/train_book.csv')

In [128]:
q.shape

(1966, 3)

In [129]:
q.genre.value_counts()

Fiction          721
 Non fiction     472
Fantasy          254
Children         183
Classics         140
Romance          139
Miscellaneous     57
Name: genre, dtype: int64

In [139]:
fict = q.loc[q.genre =='Fiction']

In [158]:
nfict= q.loc [q.genre ==' Non fiction']

In [159]:
len(fict)

721

In [160]:
len(nfict)

472

In [107]:
w = fict.index
w

Int64Index([   0,    2,   85,   86,   94,  191,  238,  239,  240,  261,
            ...
            1821, 1826, 1827, 1830, 1835, 1839, 1842, 1844, 1850, 1879],
           dtype='int64', length=721)

In [161]:
v = nfict.index

In [162]:
f = np.random.choice(w,size =250)
nf= np.random.choice(v,size =250)

In [109]:
f

array([1401, 1474,  733, 1789, 1791, 1804,  631, 1623,  482,  343, 1695,
       1500,  569, 1814, 1429, 1735, 1307, 1749,  604, 1670,  445, 1803,
       1802,  753,  704, 1531,  261, 1250,  697,  450, 1667, 1465, 1482,
       1625, 1481,  559,  519,  321, 1737,  471, 1689,  750,  528,  865,
       1720,  555, 1525, 1427,  784, 1827,  584, 1455, 1503,  617, 1718,
        563, 1815,  367, 1421,  704,  514, 1478,  565,  818,  863,  434,
        406, 1254, 1646,  519, 1580, 1406, 1545,  464, 1439,  588, 1430,
        855, 1813,  730,  468, 1544, 1420,  547,  681,  880,  537, 1027,
       1644, 1749, 1686,  879,  888,  513,  599, 1397,  863,  851,  513,
          2, 1764, 1365,  532, 1532,  713, 1772, 1740,  565, 1548,  782,
        578, 1697, 1397, 1801,  856, 1318,  734, 1521,  451,  465, 1740,
       1718,  815, 1391, 1614,  563,  590,  333,  637, 1758,  750, 1418,
       1505, 1792, 1696,  593, 1786, 1377,  874, 1522, 1352,  856, 1747,
        503, 1582,  533, 1410,  617, 1556,  532, 1531, 1694, 1471,  458,
        868,  561, 1673, 1750,  565,  781, 1797, 1679,  449,  664, 1474,
        814, 1537, 1537, 1352, 1464,  746,  716,  505,  459,  879, 1793,
       1462,  604, 1736, 1478,  759, 1712, 1782,  837,  474, 1019,  631,
        518, 1670,  872,  775,  733, 1343, 1736,  420,  275,  519, 1556,
       1312,  772, 1699, 1018, 1480,  727,  872, 1420,  881, 1800, 1223,
        465,  831,  501,  790,  607, 1670,  690, 1806, 1598,  786, 1290,
       1392, 1421,  410, 1018, 1580, 1442, 1768, 1496,  814,  668,  821,
       1525, 1774, 1625, 1662, 1494, 1526, 1367, 1501,  406, 1523, 1810,
       1514,  829, 1879,  523, 1715,  589,  806,  447])

In [163]:
nf

array([1249,  143,  119, 1884, 1269, 1058, 1306, 1876,  979, 1921,  119,
         84, 1031, 1058,   73, 1861, 1955,  957, 1931, 1044, 1028,  939,
        107, 1853,  137, 1061, 1047,  983, 1913,  122, 1867,   77, 1484,
        991,  147, 1085, 1871, 1001,   73,  986, 1553,   44,   42,   92,
       1954,   20,    3, 1084, 1825, 1921, 1872,   39,  329,  123,    7,
        989, 1004, 1437, 1396, 1186, 1070, 1893, 1866, 1925,  907,   66,
       1025, 1955,  940,    7,  928,  901,  913,  279,  129,   27, 1009,
         19, 1046,   21,  387,   88,   37, 1441, 1049,  199, 1084,   23,
       1034,  643,   80,  152,  316, 1021,  387, 1873,  947,   49,  947,
        106,   83, 1045,   67,  931,   38, 1052, 1771, 1862,   19,  983,
        122, 1912,   97,  957,  150, 1034, 1082,  653,   87, 1913, 1905,
       1855,   51, 1858,  109, 1824, 1045,   75, 1843,   48, 1836,   48,
        127, 1884, 1042,   81, 1864,   83,  179, 1938, 1050, 1921, 1862,
       1918, 1927, 1078,   32,   18,   54,  145, 1889, 1042, 1085, 1843,
        934,  984,  939, 1005, 1884, 1961, 1079, 1838,  919, 1017, 1602,
        150,   87, 1918,  124,  989, 1901, 1602, 1925,   54,  975, 1880,
       1038,  112,   19, 1965,   80, 1964,  132, 1862, 1965, 1845,   71,
       1921,  658, 1834, 1104, 1963, 1853,  638,   60,  127,   98,    1,
       1901,  962, 1931, 1896, 1898, 1860,   65,   59, 1033,  962, 1837,
       1905, 1049,   54,    8,  387, 1375, 1006, 1825, 1051, 1941, 1884,
       1949, 1052,  971, 1938, 1866, 1033,   93, 1934, 1921,   51, 1932,
        991,  117,  329,  134, 1002, 1884,  891, 1020, 1960,  964,  105,
       1913, 1947,  373,   91, 1880, 1009, 1073,  253])

In [164]:
jk = q.iloc[nf,]

In [149]:
kl = q.iloc[f,]
kl

      Unnamed: 0                                        description    genre
1401        1401  [empresswith, revolution, brewing, rhee, faced...  Fiction
1474        1474  [writer, history, win, consecutive, edgar, awa...  Fiction
733          733  [time, machine, meets, midnight, paris, determ...  Fiction
1789        1789  [evan, assassin, gone, hellbent, engrossing, u...  Fiction
1791        1791  [confront, husband, want, know, truth, twenty,...  Fiction
1804        1804  [electrifying, debut, thriller, asks, question...  Fiction
631          631  [called, lucky, seven, children, either, orpha...  Fiction
1623        1623  [loved, left, betrayed, time, open, closed, do...  Fiction
482          482  [haunted, dark, secrets, unsolved, mystery, yo...  Fiction
343          343  [petty, criminal, zara, cole, painful, past, m...  Fiction
1695        1695  [savior, salvation, jeannie, gardner, escapes,...  Fiction
1500        1500  [death, darkness, norm, black, rose, investiga...  Fiction
569          569  [inspector, esa, khattak, sergeant, rachel, ge...  Fiction
1814        1814  [ambulance, police, something, happened, know,...  Fiction
1429        1429  [lizzie, lavenza, enrolled, ingold, first, fem...  Fiction
1735        1735  [sometimes, fine, line, love, hate, humans, in...  Fiction
1307        1307  [spellbinding, tale, lonely, caregiver, cranky...  Fiction
1749        1749  [kay, donovan, may, skeletons, closet, past, p...  Fiction
604          604  [going, rogue, effort, rescue, kidnapped, pare...  Fiction
1670        1670  [percent, world, population, disappears, appar...  Fiction
445          445  [timeless, exploration, romance, lengths, go, ...  Fiction
1803        1803  [solve, murder, everyone, believes, alex, coma...  Fiction
1802        1802  [author, consistently, gives, us, suspense, ne...  Fiction
753          753  [earth, year, earth, along, entire, solar, sys...  Fiction
704          704  [stab, chilly, february, night, screening, psy...  Fiction
1531        1531  [inversgail, west, coast, scottish, highlands,...  Fiction
261          261  [story, mentally, disabled, man, whose, experi...  Fiction
1250        1250  [modern, american, literature, comes, one, boo...  Fiction
697          697  [drix, convicted, crime, one, commit, thought,...  Fiction
450          450  [extraordinary, debut, novel, freshwater, expl...  Fiction
...          ...                                                ...      ...
1392        1392  [stop, murder, already, happened, gala, party,...  Fiction
1421        1421  [linden, rose, big, secret, homeless, living, ...  Fiction
410          410  [completely, unrealistic, poorly, inspired, ex...  Fiction
1018        1018  [funny, deeply, felt, novel, illuminates, pivo...  Fiction
1580        1580  [alice, brown, fell, love, jack, day, moved, f...  Fiction
1442        1442  [trailblazing, novelist, walter, mosley, forme...  Fiction
1768        1768  [getting, used, life, back, home, deer, park, ...  Fiction
1496        1496  [truth, stay, buried, four, months, since, for...  Fiction
814          814  [one, playing, long, game, one, meet, local, t...  Fiction
668          668  [poignant, empowering, teen, novel, grief, unr...  Fiction
821          821  [triumph, swanson, name, considered, among, li...  Fiction
1525        1525  [author, consistently, gives, us, suspense, ne...  Fiction
1774        1774  [ya, sequel, cruelty, sees, gwen, face, ever, ...  Fiction
1625        1625  [new, york, times, bestselling, author, jojo, ...  Fiction
1662        1662  [warship, trouble, dog, built, bred, calculati...  Fiction
1494        1494  [many, sweets, spoil, murder, ohio, long, way,...  Fiction
1526        1526  [one, week, jessie, said, break, get, perspect...  Fiction
1367        1367  [concluding, part, science, fiction, trilogy, ...  Fiction
1501        1501  [hanson, thought, witnessed, worst, humanity, ...  Fiction
406          406  [yahiro, never, thought, would, end, prison, l...  Fiction
1523        1523  [girl, missinga, woman, searchinga, killer, pl...  Fiction
1810        1810  [isolated, swedish, town, deaf, reporter, terr...  Fiction
1514        1514  [new, release, sale, week, pink, cupcake, truc...  Fiction
829          829  [option, legendary, television, development, t...  Fiction
1879        1879  [two, girls, raped, murdered, rural, mississip...  Fiction
523          523  [warship, trouble, dog, built, bred, calculati...  Fiction
1715        1715  [author, consistently, gives, us, suspense, ne...  Fiction
589          589  [beautiful, perfect, peaceful, seaside, town, ...  Fiction
806          806  [life, luck, love, lowport, life, wags, tell, ...  Fiction
447          447  [debut, novel, set, background, hospital, roun...  Fiction

[250 rows x 3 columns]

In [167]:
df = q.loc[(q.genre!='Fiction')&(q.genre!=' Non fiction'),]

In [133]:
len(kl)

250

In [169]:
#merging dataframes 
asf = [df,fict,nfict]
f4 = pd.concat(asf)

In [172]:
f4.columns

Index(['Unnamed: 0', 'description', 'genre'], dtype='object')

In [175]:
f4.drop([1,])

,Unnamed: 0,description,genre
4,4,"[tim, burtonesque, retelling, picture, dorian,...",Children
5,5,"[one, best, things, childhood, able, imagine, ...",Children
9,9,"[relentlessly, original, brilliantly, hybrid, ...",Fantasy
10,10,"[dazzling, picture, book, biography, one, worl...",Children
11,11,"[art, widely, accepted, art, serves, important...",Fantasy
13,13,"[incredible, story, world, largest, visionary,...",Children
16,16,"[time, anniversary, trump, inauguration, women...",Miscellaneous
30,30,"[dazzling, picture, book, biography, one, worl...",Children
33,33,"[barry, wittenstein, clearly, great, sense, hu...",Children
34,34,"[incredible, story, world, largest, visionary,...",Children
52,52,"[charming, accessible, picture, book, ian, len...",Children
55,55,"[new, york, times, bestseller, badass, book, p...",Miscellaneous
74,74,"[kevin, horsley, broke, world, memory, record,...",Miscellaneous
78,78,"[forty, years, ago, israeli, psychologists, da...",Miscellaneous
79,79,"[groundbreaking, analysis, personality, type, ...",Miscellaneous
89,89,"[captivating, new, sexy, standalone, romance, ...",Romance
121,121,"[two, decades, legendary, trainer, tim, grover...",Miscellaneous
131,131,"[retired, general, bestselling, author, share,...",Miscellaneous
133,133,"[raghuram, rajan, took, charge, governor, rese...",Miscellaneous
136,136,"[creator, dilbert, unflinching, look, strategi...",Miscellaneous
141,141,"[new, york, times, bestsellerwall, street, jou...",Miscellaneous
153,153,"[champions, sweep, follow, keep, blue, legacy,...",Miscellaneous
154,154,"[meet, kiranmala, interdimensional, demonslaye...",Fantasy
155,155,"[problim, children, ramshackle, bungalow, swam...",Children
156,156,"[brian, selznick, honey, got, look, well, good...",Children
157,157,"[claire, martinson, still, worries, older, sis...",Fantasy
158,158,"[marabel, must, defy, expectations, rescue, br...",Fantasy
160,160,"[start, ali, fadhil, consumed, love, soccer, v...",Children
161,161,"[ten, years, alex, aaron, stowe, brought, peac...",Fantasy
162,162,"[wishes, magic, dares, abound, tween, math, wh...",Children
...,...,...,...
1933,1933,"[remarkable, untold, story, thomas, jefferson,...",Non fiction
1934,1934,"[extraordinary, look, means, grow, old, hearte...",Non fiction
1935,1935,"[new, york, times, bestseller, bestselling, au...",Non fiction
1937,1937,"[spectacular, true, story, scrappy, teenager, ...",Non fiction
1938,1938,"[first, definitive, history, mossad, shin, bet...",Non fiction
1939,1939,"[elevator, door, opens, cow, stands, inside, a...",Non fiction
1940,1940,"[trump, administration, remaking, government, ...",Non fiction
1941,1941,"[powerful, investigative, look, technology, af...",Non fiction
1942,1942,"[new, york, times, bestselling, author, simon,...",Non fiction
1943,1943,"[new, approach, romance, heroines, regency, no...",Non fiction
1944,1944,"[explodes, fables, created, civil, rights, mov...",Non fiction
1945,1945,"[anthology, heart, powerful, emotion, edited, ...",Non fiction
1946,1946,"[fiercely, courageous, account, one, woman, un...",Non fiction
1947,1947,"[discovered, michael, ondaatje, davies, dazzli...",Non fiction
1948,1948,"[book, ancient, call, first, mothers, connect,...",Non fiction
1949,1949,"[inspirational, story, pregnant, young, nigeri...",Non fiction
1950,1950,"[intersectional, history, shared, struggle, af...",Non fiction
1951,1951,"[chronicling, adventurous, life, legendary, ci...",Non fiction
1952,1952,"[bill, minutaglio, steven, davis, authors, pen...",Non fiction
1954,1954,"[year, calamitous, events, one, pivotal, impor...",Non fiction
1955,1955,"[first, things, first, man, shaming, said, rec...",Non fiction
1957,1957,"[author, new, york, times, bestseller, crisis,...",Non fiction
1958,1958,"[many, us, suffer, depression, anxiety, simple...",Non fiction
1959,1959,"[scientific, exploration, humanity, obsession,...",Non fiction
1960,1960,"[telling, stories, six, pioneering, african, a...",Non fiction
1961,1961,"[youtube, head, culture, trends, rousing, illu...",Non fiction
1962,1962,"[dramatic, rethinking, encounter, montezuma, h...",Non fiction
1963,1963,"[anjali, kumar, member, rapidly, growing, cont...",Non fiction
1964,1964,"[highly, recommend, feminist, activists, pov, ...",Non fiction
1965,1965,"[legendary, icon, tells, tale, art, passion, c...",Non fiction

In [183]:
f4.to_csv('mod_train.csv')

In [181]:
f4.columns

Index(['Unnamed: 0', 'description', 'genre'], dtype='object')

In [171]:
f4.reset_index(drop = True)

,Unnamed: 0,description,genre
0,4,"[tim, burtonesque, retelling, picture, dorian,...",Children
1,5,"[one, best, things, childhood, able, imagine, ...",Children
2,9,"[relentlessly, original, brilliantly, hybrid, ...",Fantasy
3,10,"[dazzling, picture, book, biography, one, worl...",Children
4,11,"[art, widely, accepted, art, serves, important...",Fantasy
5,13,"[incredible, story, world, largest, visionary,...",Children
6,16,"[time, anniversary, trump, inauguration, women...",Miscellaneous
7,30,"[dazzling, picture, book, biography, one, worl...",Children
8,33,"[barry, wittenstein, clearly, great, sense, hu...",Children
9,34,"[incredible, story, world, largest, visionary,...",Children
10,52,"[charming, accessible, picture, book, ian, len...",Children
11,55,"[new, york, times, bestseller, badass, book, p...",Miscellaneous
12,74,"[kevin, horsley, broke, world, memory, record,...",Miscellaneous
13,78,"[forty, years, ago, israeli, psychologists, da...",Miscellaneous
14,79,"[groundbreaking, analysis, personality, type, ...",Miscellaneous
15,89,"[captivating, new, sexy, standalone, romance, ...",Romance
16,121,"[two, decades, legendary, trainer, tim, grover...",Miscellaneous
17,131,"[retired, general, bestselling, author, share,...",Miscellaneous
18,133,"[raghuram, rajan, took, charge, governor, rese...",Miscellaneous
19,136,"[creator, dilbert, unflinching, look, strategi...",Miscellaneous
20,141,"[new, york, times, bestsellerwall, street, jou...",Miscellaneous
21,153,"[champions, sweep, follow, keep, blue, legacy,...",Miscellaneous
22,154,"[meet, kiranmala, interdimensional, demonslaye...",Fantasy
23,155,"[problim, children, ramshackle, bungalow, swam...",Children
24,156,"[brian, selznick, honey, got, look, well, good...",Children
25,157,"[claire, martinson, still, worries, older, sis...",Fantasy
26,158,"[marabel, must, defy, expectations, rescue, br...",Fantasy
27,160,"[start, ali, fadhil, consumed, love, soccer, v...",Children
28,161,"[ten, years, alex, aaron, stowe, brought, peac...",Fantasy
29,162,"[wishes, magic, dares, abound, tween, math, wh...",Children
...,...,...,...
1936,1933,"[remarkable, untold, story, thomas, jefferson,...",Non fiction
1937,1934,"[extraordinary, look, means, grow, old, hearte...",Non fiction
1938,1935,"[new, york, times, bestseller, bestselling, au...",Non fiction
1939,1937,"[spectacular, true, story, scrappy, teenager, ...",Non fiction
1940,1938,"[first, definitive, history, mossad, shin, bet...",Non fiction
1941,1939,"[elevator, door, opens, cow, stands, inside, a...",Non fiction
1942,1940,"[trump, administration, remaking, government, ...",Non fiction
1943,1941,"[powerful, investigative, look, technology, af...",Non fiction
1944,1942,"[new, york, times, bestselling, author, simon,...",Non fiction
1945,1943,"[new, approach, romance, heroines, regency, no...",Non fiction
1946,1944,"[explodes, fables, created, civil, rights, mov...",Non fiction
1947,1945,"[anthology, heart, powerful, emotion, edited, ...",Non fiction
1948,1946,"[fiercely, courageous, account, one, woman, un...",Non fiction
1949,1947,"[discovered, michael, ondaatje, davies, dazzli...",Non fiction
1950,1948,"[book, ancient, call, first, mothers, connect,...",Non fiction
1951,1949,"[inspirational, story, pregnant, young, nigeri...",Non fiction
1952,1950,"[intersectional, history, shared, struggle, af...",Non fiction
1953,1951,"[chronicling, adventurous, life, legendary, ci...",Non fiction
1954,1952,"[bill, minutaglio, steven, davis, authors, pen...",Non fiction
1955,1954,"[year, calamitous, events, one, pivotal, impor...",Non fiction
1956,1955,"[first, things, first, man, shaming, said, rec...",Non fiction
1957,1957,"[author, new, york, times, bestseller, crisis,...",Non fiction
1958,1958,"[many, us, suffer, depression, anxiety, simple...",Non fiction
1959,1959,"[scientific, exploration, humanity, obsession,...",Non fiction
1960,1960,"[telling, stories, six, pioneering, african, a...",Non fiction
1961,1961,"[youtube, head, culture, trends, rousing, illu...",Non fiction
1962,1962,"[dramatic, rethinking, encounter, montezuma, h...",Non fiction
1963,1963,"[anjali, kumar, member, rapidly, growing, cont...",Non fiction
1964,1964,"[highly, recommend, feminist, activists, pov, ...",Non fiction
1965,1965,"[legendary, icon, tells, tale, art, passion, c...",Non fiction